### ISSUE TITLE
no maven deploy in directory

### ISSUE THREAD

**Issue by berndhopp** [elmot/vaadin-geo-location-flow#1]
In the directory, it says that "This component or version has not been published in Maven.". This is maybe due to a missing license.

**Comment by elmot** [comment]
The license is set to MIT

**Comment by berndhopp** [comment]
I see, you're right. But anyways, it doesn't seem to be deployed to maven for some reason.

**Comment by elmot** [comment]
Fixed with setting of supported framework version
